name: Desafio CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

defaults:
  run:
    working-directory: ./src/full-cycle-desafio-ci

jobs:
  desafio-ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: go test
      env: ['GOPATH=.']