name: Desafio CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  desafio-ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: go test
      env: ['GOPATH=.']